dist: trusty
sudo: false

language:
  - python
  - node_js

python:
  - "2.7"
  - "3.3"

node_js:
  - "node"

#
# limit clone depth to 3, to speed up build:
git:
  depth: 3

cache:
  directories:
    - $HOME/.pylint.d

install:
  - bash scripts/install.sh

script:
  - bash scripts/run_tests.sh

notifications:
  email:
    on_success: never
    on_failure: always
